

# ================================ DOCKER COMPOSE WEBHOOK ==============================
_DOCKER_COMPOSE_WEBHOOK = """services:
    whatsapp-webhook:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "{PORT}:{PORT}"
        environment:
            - 
        restart: unless-stopped
"""

# ================================ DOCKERFILE WEBHOOK ==============================
_DOCKERFILE_WEBHOOK="""FROM python:{PYTHON_VERSION}-slim
WORKDIR /app

COPY {REQUIREMENTS_DIR} /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY {WEBHOOK_DIR} /app/webhook/

EXPOSE {PORT}
CMD ["uvicorn", "webhook.main_webhook:app", "--host", "localhost", "--port", "{PORT}"]
"""

# ================================ DOTENV COMPOSE WEBHOOK ==============================
_DOTENV_COMPOSE_WEBHOOK = """# =========================================
# Webhook de WhatsApp Toolkit - configuración de Docker Compose
# =========================================


port={PORT}
"""

# =============================== REQUIREMENTS WEBHOOK ==============================
_REQUIREMENTS_WEBHOOK = """# This file was autogenerated by uv via the following command:
#    uv export --format requirements-txt --no-hashes

annotated-doc==0.0.4
    # via fastapi
annotated-types==0.7.0
    # via pydantic
anyio==4.12.0
    # via starlette
certifi==2025.11.12
    # via requests
charset-normalizer==3.4.4
    # via
    #   reportlab
    #   requests
click==8.3.1
    # via uvicorn
colorama==0.4.6 ; sys_platform == 'win32'
    # via
    #   click
    #   qrcode
coloredlogs==15.0.1
    # via onnxruntime
colorstreak==2.1.0
    # via whatsapp-toolkit
python-dotenv==1.2.1
    # via whatsapp-toolkit
exceptiongroup==1.3.1 ; python_full_version < '3.11'
    # via anyio
fastapi==0.124.4
    # via whatsapp-toolkit
flatbuffers==25.9.23
    # via onnxruntime
h11==0.16.0
    # via uvicorn
humanfriendly==10.0
    # via coloredlogs
idna==3.11
    # via
    #   anyio
    #   requests
mpmath==1.3.0
    # via sympy
numpy==2.2.6 ; python_full_version < '3.11'
    # via onnxruntime
numpy==2.3.5 ; python_full_version >= '3.11'
    # via onnxruntime
onnxruntime==1.23.2
    # via piper-tts
packaging==25.0
    # via onnxruntime
pillow==12.0.0
    # via
    #   reportlab
    #   whatsapp-toolkit
piper-tts==1.3.0
    # via whatsapp-toolkit
platformdirs==4.5.1
    # via whatsapp-toolkit
protobuf==6.33.2
    # via onnxruntime
pydantic==2.12.5
    # via fastapi
pydantic-core==2.41.5
    # via pydantic
pyreadline3==3.5.4 ; sys_platform == 'win32'
    # via humanfriendly
python-dotenv==1.2.1
    # via dotenv
qrcode==8.2
    # via whatsapp-toolkit
reportlab==4.4.6
    # via whatsapp-toolkit
requests==2.32.5
    # via whatsapp-toolkit
starlette==0.50.0
    # via fastapi
sympy==1.14.0
    # via onnxruntime
typing-extensions==4.15.0
    # via
    #   anyio
    #   exceptiongroup
    #   fastapi
    #   pydantic
    #   pydantic-core
    #   starlette
    #   typing-inspection
    #   uvicorn
typing-inspection==0.4.2
    # via pydantic
urllib3==2.6.1
    # via requests
uvicorn==0.38.0
    # via whatsapp-toolkit
"""



# =============================== DOTENV WEBHOOK ==============================
_DOTENV_WEBHOOK = """# =========================================
# Webhook de WhatsApp Toolkit (Python) - configuración local/dev
# =========================================
# NOTA:
# - Este es un archivo de creado automaticamente si cambias algo reinica el docker.

WHATSAPP_API_KEY={API_KEY}
"""

# ================================ MINIMAL PYTHON SCRIPT ==============================
_MAIN_WEBHOOK_PY ="""
# Instala haciendo: 
# pip install fastapi uvicorn python-dotenv whatsapp-toolkit
# O usa (SUGERIDO): 
# uv add  fastapi uvicorn python-dotenv whatsapp-toolkit


#from whatsapp_toolkit import webhook
from fastapi import FastAPI
from dotenv import load_dotenv
import os


load_dotenv()


app = FastAPI(
    title="whatsapp-toolkit | Webhook",
    description="A simple WhatsApp webhook using WhatsApp Toolkit and FastAPI",
    version="1.0.0",
    debug=True,
    docs_url="/doc",
)



@app.get("/webhook/whatsapp/health", tags=["WhatsApp Webhook"])
def whatsapp_webhook():
    mensaje = "Todo OK"
    return {"status_code": 200, "message": mensaje}


"""
